routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function()
    {
    /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    Auth::routes(['verify' => true]);

    Route::get('/','HomeController@index');

    Route::resource('posts','PostController');

    /** normal user routes **/
    Route::group([
        'middleware'=>['auth','verified']
        ],function(){
        Route::get('/session', 'HomeController@session')->name('session');
        Route::get('/home', 'HomeController@index')->name('home');
    });


    /** admin routes **/
    Route::group(
        [
            'prefix'=>'cpanel',
            'middleware'=>['auth','verified','roles'],
            'roles'=>'admin'
        ],
        function(){
            Route::resource('home','Cpanel\CPHomeController');
            Route::resource('/','Cpanel\CPHomeController');
            Route::resource('admins','Cpanel\CPAdminsController')->except('show');
            Route::resource('categories','Cpanel\CPCategoriesController')->except('show');
            Route::resource('products','Cpanel\CPProductsController')->except('show');
    });
});

app/Http/Controllers/Cpanel/CPAdminsController.php
<?php

namespace App\Http\Controllers\Cpanel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use App\User;
use Auth;
use Image; 
use Storage;

class CPAdminsController extends Controller
{
    public function __construct(){
        $this->middleware(['permission:create_users'])->only(['create','store']);
        $this->middleware(['permission:update_users'])->only(['edit','update']);
        $this->middleware(['permission:read_users'])->only('index');
        $this->middleware(['permission:delete_users'])->only('destroy');
    }

    public function index(Request $request)
    {
       /*
            search without checking if role is admin
        if($request->search){
            $users = User::where('first_name','like','%'.$request->search.'%')
            ->orWhere('last_name','like','%'.$request->search.'%')
            ->orWhere('email','like','%'.$request->search.'%')
            ->get();
        }else{
            $users = User::whereRoleIs('admin')->get();
        }
        
        */
        
        if($request->ajax()){
            return DataTables(User::WhereRoleIs('admin'))
            ->addColumn('actions',"cpanel.admins.dt_cols.actions")
            ->addColumn('user_image',"cpanel.admins.dt_cols.user_image")
            ->rawColumns(['actions','user_image'])
            ->toJson();
        }
        
        $users = User::WhereRoleIs('admin')->where(function($e) use ($request){
            // rules after where role is admin
            return $e->when($request->search,function($query) use ($request) {
                // rules after when request search
                return $query->where('first_name','like','%'.$request->search.'%')
                ->orWhere('last_name','like','%'.$request->search.'%')
                ->orWhere('email','like','%'.$request->search.'%');
            });
        })->get();

        return view('cpanel.admins.index');
    }

    public function create()
    {
        return view('cpanel.admins.create');
    }


    public function store(Request $request)
    {        
        $request->validate([
            'first_name' => 'bail|required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8|confirmed',
            'permissions' => 'required',
            'photo' => 'image'
        ]);

        $request_data = $request->except(['password','password_confirmation','permissions','photo']);
        $request_data['password'] = bcrypt($request->password);

        // Photo 

        if($request->photo){

            $img = Image::make($request->photo);
            
            $img->resize(150, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path('uploads/users_images/'.$request->photo->hashName()));

            $request_data['photo'] = $request->photo->hashName();
        }

        $user = User::create($request_data);
        $user->attachRole('admin');
        $user->attachPermissions($request->permissions);
        return redirect(route('admins.index'))->with('success',__('site.admin_added_success'));
    }

    public function edit($id)
    {
        $user = User::find($id);
        return view('cpanel.admins.edit',compact('user'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => ['required','string','email',Rule::unique('users')->ignore($id)],
            'photo' => 'image',
            'permissions' => 'required'
        ]);

        $user = User::find($id);

        $request_data = $request->except(['password','password_confirmation','permissions','photo']);

        if($request->photo){

            if($user->photo != 'default.png'){
                Storage::disk('public_uploads')->delete('/users_images/'.$user->photo);
            }

            $img = Image::make($request->photo);
            
            $img->resize(150, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path('uploads/users_images/'.$request->photo->hashName()));

            $request_data['photo'] = $request->photo->hashName();
        }

        $user->update($request_data);
        //detach old permissions 
        $user->detachPermissions($user->permissions);
        // attach new permissions 
        $user->attachPermissions($request->permissions);
        
        return redirect( route('admins.index') )->with('success',__('site.admin_updated_success'));
    }

    public function destroy($id)
    {
        if(Auth::id() == $id){
            return redirect( route('admins.index') )->with('error',__('site.error_self_delete'));
        }

        
        $user = User::find($id);

        // delete user image
        if($user->photo != 'default.png'){
            Storage::disk('public_uploads')->delete('/users_images/'.$user->photo);
        }

        if($user->hasRole('super_admin')){
            return redirect( route('admins.index') )->with('error',__('site.error_super_admin_delete'));
        }
        if($user->delete()){
            return redirect( route('admins.index') )->with('success',__('site.delete_success',[ 'name' => $user->first_name.' '.$user->last_name ]));
        }
    }
}

app/Http/Controllers/Cpanel/CPCategoriesController.php
<?php
namespace App\Http\Controllers\Cpanel;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;

class CPCategoriesController extends Controller
{
    public function __construct(){
        $this->middleware(['permission:create_categories'])->only(['create','store']);
        $this->middleware(['permission:update_categories'])->only(['edit','update']);
        $this->middleware(['permission:read_categories'])->only('index');
        $this->middleware(['permission:delete_categories'])->only('destroy');
    }
    public function index(Request $request)
    {
        if($request->ajax()){
            return DataTables(Category::all())
            ->addColumn('actions','cpanel.categories.dt_cols.actions')
            ->rawColumns(['actions'])
            ->toJson();
        }
        return view('cpanel.categories.index');
    }

    public function create()
    {
        return view('cpanel.categories.create');
    }

    public function store(Request $request)
    {
        $locales = config('translatable.locales');
        $validation = [];

        foreach($locales as $locale){
            $validation[$locale.'.name'] = 'required|unique:category_translations,name';
        }

        $request->validate($validation);
        
        Category::Create($request->all());
        return redirect( route('categories.index') )->with(['success'=>'category created successfully !']);
        
    }

    public function edit(category $category)
    {
        return view('cpanel.categories.edit',compact('category'));
    }

    public function update(Request $request, category $category)
    {
        $locales = config('translatable.locales');
        $validation = [];
        
        foreach($locales as $locale){
            $validation[$locale.'.name'] = [Rule::unique('category_translations','name')->ignore($category->id, 'category_id'),'required'];
        }

        $request->validate($validation);

        $category->update($request->all());
        return redirect( route('categories.index') )->with(['success'=>'category updated successfully !']); 
    }

    public function destroy(category $category)
    {
        $category->delete();
        return redirect( route('categories.index') )->with(['success'=>'category deleted successfully !']); 
    }
}

app/Http/Controllers/Cpanel/CPHomeController.php
<?php

namespace App\Http\Controllers\Cpanel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CPHomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('cpanel.adminHome');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Cpanel/CPProductsController.php
<?php

namespace App\Http\Controllers\Cpanel;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;

class CPProductsController extends Controller
{
    public function __construct(){
        $this->middleware(['permission:create_products'])->only(['create','store']);
        $this->middleware(['permission:update_products'])->only(['edit','update']);
        $this->middleware(['permission:read_products'])->only('index');
        $this->middleware(['permission:delete_products'])->only('destroy');
    }

    public function index(Request $request)
    {
        return view('cpanel.products.index');
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function edit(Product $product)
    {
        //
    }

    public function update(Request $request, Product $product)
    {
        //
    }

    public function destroy(Product $product)
    {
        //
    }
}

resources/views/cpanel/admins/create.blade.php
{{-- resources/views/admin/dashboard.blade.php --}}

@extends('adminlte::page')

@section('title')
  @lang('site.add_admin')
@stop
@section('content_header')
    <h1>@lang('site.add_admin'):</h1>
    {{ Breadcrumbs::render('create_users') }}
@stop

@section('content')

<div class="row ">
    <div class="col-md-12">

                <div class="box box-info">

                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1">

                                <form action="{{ route('admins.store') }}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    <!-- First Name -->
                                    <div class="form-group @error('first_name') has-error @enderror">
                                        <label>@lang('site.first_name'):</label>
                                        <input type="text" class="form-control" name="first_name" value="{{ old('first_name') }}">
                                        @if($errors->has('first_name'))
                                            <span class="text text-danger">@error('first_name')
                                            {{ $message }}
                                            @enderror</span>
                                        @endif
                                    </div>

                                    <!-- Last Name -->
                                    <div class="form-group {{ $errors->has('last_name') ? 'has-error' : ''}}">
                                        <label>@lang('site.last_name'):</label>
                                        <input type="text" class="form-control" name="last_name" value="{{ old('last_name') }}">
                                        @if($errors->has('last_name'))
                                            <span class="text text-danger">{{ $errors->first('last_name') }}</span>
                                        @endif
                                    </div>

                                    <!-- Email -->
                                    <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                                        <label>@lang('site.email'):</label>
                                        <input type="text" class="form-control " name="email" value="{{ old('email') }}">
                                        @if($errors->has('email'))
                                            <span class="text text-danger">{{ $errors->first('email') }}</span>
                                        @endif

                                    </div>   


                                    <!-- Photo -->
                                    <div class="form-group {{ $errors->has('photo') ? 'has-error' : '' }}">
                                        <label>@lang('site.photo'):</label>
                                        <input type="file" class="" name="photo" value="{{ old('photo') }}" />
                                        @if($errors->has('photo'))
                                            <span class="text text-danger">{{ $errors->first('photo') }}</span>
                                        @endif

                                    </div>
                                    <!-- Preview Photo -->
                                    <div class="form-group">
                                        <img src="{{ asset('uploads/users_images/default.png') }}" alt="" width="70" class="img img-responsive img-preview">
                                    </div>  

                                    <!-- Password -->
                                    <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                                        <label>@lang('site.password'):</label>
                                        <input type="text" class="form-control" name="password">
                                        @if($errors->has('password'))
                                            <span class="text text-danger">{{ $errors->first('password') }}</span>
                                        @endif
                                    </div> 

                                    <!-- Confirm Password -->
                                    <div class="form-group">
                                        <label>@lang('site.confirm_password'):</label>
                                        <input type="text" class="form-control" name="password_confirmation">
                                    </div>   
                                    
                                    <!-- Permissions -->
                                    @php 
                                        //$models = ['users','categories','posts'];
                                        $models = config('laratrust_seeder.role_structure.super_admin');
                                        $map = config('laratrust_seeder.permissions_map');
                                        $i = 0;
                                
                                    @endphp

                                   <div class="form-group">
                                       <label for="">@lang('site.permissions'):</label>
                                       <div class="nav-tabs-custom">
                                        <ul class="nav nav-tabs">
                                            @php $i = 0; @endphp
                                            @foreach($models as $key=>$value)
                                               
                                                <li class="{{ $i == 0 ? 'active' : '' }}"><a href="#{{ $key }}" data-toggle="tab">@lang('site.'.$key)</a></li>
                                                @php $i++ @endphp
                                            @endforeach
                                        </ul>

                                        <div class="tab-content">
                                            @php $i = 0; @endphp
                                            @foreach($models as $model=>$crud)
                                                <div class="tab-pane {{ $i == 0 ? 'active' : '' }}" id="{{ $model }}">

                                                    <div class="form-group">
                                                    @php $crud = explode(',',$crud) @endphp
                                                    @foreach($crud as $index=>$permission)
                                                      
                                                        @if(!empty($permission) && array_key_exists($permission, $map))
                                                            <label>
                                                                <input type="checkbox" {{ $index == 1 ? 'checked' : '' }} class="flat-red" name="permissions[]" value="{{ $map["$permission"].'_'.$model }}"> @lang('site.'.$map["$permission"]) 
                                                            </label>
                                                        @endif
                                                          
                                                    @endforeach
                                      
                                                    </div>

                                                </div>
                                                @php $i++ @endphp
                                            @endforeach
                        
                                            
                                            <!-- /.tab-pane -->
                                        </div>
                                        <!-- /.tab-content -->
                                    </div>
                                    @error('permissions')
                                      <span class="text text-danger">{{ $message }}</span>
                                    @enderror
                                   </div>
                                    <!-- Submit -->
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary">@lang('site.add')</button>
                                    </div>                                
                                </form>

                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->

                </div>
                <!-- /.box -->
    </div>
</div>

@stop

resources/views/cpanel/admins/edit.blade.php
{{-- resources/views/admin/dashboard.blade.php --}}

@extends('adminlte::page')

@section('title')
  @lang('site.add_admin')
@stop
@section('content_header')
    <h1>@lang('site.add_admin'):</h1>
    {{ Breadcrumbs::render('edit_users',$user) }}
@stop

@section('content')

<div class="row ">
    <div class="col-md-12">


                <div class="box box-info">

                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1">

                                <form action="{{ route('admins.update',$user->id) }}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <!-- First Name -->
                                    <div class="form-group @error('first_name') has-error @enderror">
                                        <label>@lang('site.first_name'):</label>
                                        <input type="text" class="form-control" name="first_name" value="{{ $user->first_name }}">
                                        @if($errors->has('first_name'))
                                            <span class="text text-danger">@error('first_name')
                                            {{ $message }}
                                            @enderror</span>
                                        @endif
                                    </div>

                                    <!-- Last Name -->
                                    <div class="form-group {{ $errors->has('last_name') ? 'has-error' : ''}}">
                                        <label>@lang('site.last_name'):</label>
                                        <input type="text" class="form-control" name="last_name" value="{{ $user->last_name }}">
                                        @if($errors->has('last_name'))
                                            <span class="text text-danger">{{ $errors->first('last_name') }}</span>
                                        @endif
                                    </div>

                                    <!-- Email -->
                                    <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                                        <label>@lang('site.email'):</label>
                                        <input type="text" class="form-control " name="email" value="{{ $user->email }}">
                                        @if($errors->has('email'))
                                            <span class="text text-danger">{{ $errors->first('email') }}</span>
                                        @endif

                                    </div> 

                                    <!-- Photo -->
                                    <div class="form-group {{ $errors->has('photo') ? 'has-error' : '' }}">
                                        <label>@lang('site.photo'):</label>
                                        <input type="file" class="" name="photo"/>
                                        @if($errors->has('photo'))
                                            <span class="text text-danger">{{ $errors->first('photo') }}</span>
                                        @endif

                                    </div>
                                    <!-- Preview Photo -->
                                    <div class="form-group">
                                        <img src="{{ $user->image_path }}" alt="" id="image-preview" width="70" class="img img-responsive img-preview">
                                    </div>  

                                    <!-- Permissions -->
                                    @php 
                                        //$models = ['users','categories','posts'];
                                        $models = config('laratrust_seeder.role_structure.super_admin');
                                        $map = config('laratrust_seeder.permissions_map');
                                        $i = 0;
                                
                                    @endphp

                                   <div class="form-group">
                                       <label for="">@lang('site.permissions'):</label>
                                       <div class="nav-tabs-custom">
                                        <ul class="nav nav-tabs">
                                            @php $i = 0; @endphp
                                            @foreach($models as $key=>$value)
                                                <li class="{{ $i == 0 ? 'active' : '' }}"><a href="#{{ $key }}" data-toggle="tab">@lang('site.'.$key)</a></li>
                                                @php $i++ @endphp
                                            @endforeach
                                        </ul>

                                        <div class="tab-content">
                                            @php $i = 0; @endphp
                                            @foreach($models as $model=>$crud)

                                                <div class="tab-pane {{ $i == 0 ? 'active' : '' }}" id="{{ $model }}">

                                                    <div class="form-group">
                                                    @php $crud = explode(',',$crud) @endphp
                                                    @foreach($crud as $index=>$permission)
                                                    
                                                    <label>
                                                        <input type="checkbox" {{ $user->hasPermission($map["$permission"].'_'.$model) ? 'checked' : '' }} class="flat-red" name="permissions[]" value="{{ $map["$permission"].'_'.$model }}"> @lang('site.'.$map["$permission"]) 
                                                    </label>
                                                          
                                                    @endforeach
                                      
                                                    </div>

                                                </div>
                                                @php $i++ @endphp
                                            @endforeach
                        
                                            
                                            <!-- /.tab-pane -->
                                        </div>
                                        <!-- /.tab-content -->
                                    </div>
                                    @error('permissions')
                                      <span class="text text-danger">{{ $message }}</span>
                                    @enderror
                                   </div>
                                    <!-- Submit -->
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary">@lang('site.update')</button>
                                    </div>                                
                                </form>

                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->

                </div>
                <!-- /.box -->
    </div>
</div>

@stop

resources/views/cpanel/admins/index.blade.php
{{-- resources/views/admin/dashboard.blade.php --}}

@extends('adminlte::page')

@section('title')
    @lang('site.admins')
@stop

@section('content_header')
    <h1>@lang('site.admins')</h1>
    {{ Breadcrumbs::render('admins') }}
@stop

@section('content')

<div class="box box-primary">
            <div class="box-header">
            <div class="row">
                <div class="col-md-8">
                    <!-- Create Admin -->

                    @if(auth::User()->can('create_users'))
                        <a class="btn btn-primary" href="{{ route('admins.create') }}"><i class="fa fa-plus"></i> @lang('site.add_admin')</a>
                        @else
                        <a class="btn btn-primary disabled" href="#"><i class="fa fa-plus"></i> @lang('site.add_admin')</a>
                    @endif

                </div>

                <div class="col-md-4">
                    
                </div>
            </div>
            
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-responsive" id="datatable">
              <thead>
                    <tr>
                        <th>#</th>
                        <th>@lang('site.first_name')</th>
                        <th>@lang('site.last_name')</th>
                        <th>@lang('site.email')</th>
                        <th>@lang('site.photo')</th>
                        <th>@lang('site.roles')</th>
                        <th>@lang('site.actions')</th>
                    </tr>
              </thead>
               
              </table>
            </div>
            <!-- /.box-body -->
          </div>
@stop

@section('js')
<script>

        $('#datatable').DataTable({
            responsive : true,
            processing : true,
            ajax : '{{ route('admins.index') }}',
            columns : [
                {'data' : 'id'},
                {'data' : 'first_name'},
                {'data' : 'last_name'},
                {'data' : 'email'},
                {'data' : 'user_image'},
                {'data' : 'user_roles'},
                {'data' : 'actions'},
            ],

        });
    </script>   
@stop