routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function()
    {
    /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    Auth::routes(['verify' => true]);

    Route::get('/','HomeController@index');

    Route::resource('posts','PostController');

    /** normal user routes **/
    Route::group([
        'middleware'=>['auth','verified']
        ],function(){
        Route::get('/session', 'HomeController@session')->name('session');
        Route::get('/home', 'HomeController@index')->name('home');
    });


    /** admin routes **/
    Route::group(
        [
            'prefix'=>'cpanel',
            'middleware'=>['auth','verified','roles'],
            'roles'=>'admin'
        ],
        function(){
            Route::resource('home','Cpanel\CPHomeController');
            Route::resource('/','Cpanel\CPHomeController');
            Route::resource('admins','Cpanel\CPAdminsController')->except('show');
            Route::resource('categories','Cpanel\CPCategoriesController')->except('show');
            Route::resource('products','Cpanel\CPProductsController')->except('show');
    });
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class category extends Model
{
    use \Dimsav\Translatable\Translatable;
    
    public $translatedAttributes = ['name'];
    protected $guarded = [];
}

resources/views/cpanel/categories/dt_cols/actions.blade.php
@if(auth::User()->can('update_categories') )
<a class="btn btn-success btn-xs" href="{{ route('categories.edit',$id) }}"><i class="fa fa-edit"></i> @lang('site.edit')</a>
@else
<a class="btn btn-success disabled btn-xs" href="#"><i class="fa fa-edit"></i> @lang('site.edit')</a>
@endif

@if(auth::User()->can('delete_categories') )
<button type="submit" class="btn btn-danger btn-xs delete" data-user_id="{{ $id }}" data-user_name="{{ $name }}"> <i class="fa fa-trash"></i>
@lang('site.delete')</button>
<form action="{{ route('categories.destroy',$id) }}" id="form_{{ $id }}" method="post" style="display:inline-block;">
    @csrf
    @method('delete')
</form>
@else
<a href="#" class="btn btn-danger disabled btn-xs"><i class="fa fa-trash"></i> @lang('site.delete')</a>
@endif

resources/views/cpanel/categories/dt_cols/user_image.blade.php
<img src="{{ $image_path }}" class="img img-responsive" width="70px" />